from random import randint


def checker(computerGeneratedNumber, userEnteredNumber):
    print(f"Numbers generated by computer = {computerGeneratedNumber}")
    print(f"User entered values = {userEnteredNumber}")

    matched = True
    for i in range(len(computerGeneratedNumber)):
        if computerGeneratedNumber[i] != userEnteredNumber[i]:
            matched = False

    if matched == True:
        print("Congratulations!! You won.")
        print("Your $100 cash prize will be coming their way soon!")
    else:
        print("Nice try, better luck next time around")


def main():
    computerGeneratedNumber = []
    userEnteredNumber = []

    for i in range(3):
        computerGeneratedNumber.append(randint(1, 9))
    computerGeneratedNumber.sort()

    print("Enter three integers")
    for i in range(3):
        num = int(input())
        userEnteredNumber.append(num)
    userEnteredNumber.sort()

    checker(computerGeneratedNumber, userEnteredNumber)


main()
